spring:
  #mysql
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/identity
  #    username: root
  #    password: rootpassword
  #    driver-class-name: com.mysql.cj.jdbc.Driver

  #H2 db test only
  datasource:
    url: jdbc:h2:file:./data/identityService
    driver-class-name: org.h2.Driver
    username: sa
    password: sapassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
  servlet:
    context-path: /identity
